name: Build LaTeX document
on: [push]
permissions:
  contents: write
  discussions: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: document.tex
          extra_system_packages: "inkscape"
          args: -f -jobname=document -pdf -file-line-error -shell-escape -interaction=nonstopmode -synctex=1
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: document.pdf
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          name: Build
          body: build
          tag_name: pdf
          files: |
            document.pdf
      # - name: Publish HTML to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: /
